services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music_website_SAM_apache
    ports:
      - "8080:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/storage/logs
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: music_website_SAM_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: music_website_SAM_system
      MYSQL_USER: dumitru
      MYSQL_PASSWORD: 3412760
      MYSQL_ROOT_PASSWORD: 34127600
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
